apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/kube-prometheus/

patchesStrategicMerge:
- alertmanager-service.yaml
- prometheus-service.yaml
- grafana-service.yaml
