apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: rook-ceph-operator
  namespace: argocd
spec:
  source:
    path: ./infra-apps/other/rook-ceph/apps/rook-ceph-operator
    repoURL: 'https://github.com/ryourst/infra-apps'
    targetRevision: main
  destination:
    namespace: rook-ceph
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
